fun main(){
   print("Student Enrollment No. : ")
   val Enrollment = readln().toLong()
   print("Student Name : ")
   val Name = readln()
   print("Student Branch : ")
   val Branch = readln()
   print("Student Class : ")
   val Class = readln()
   print("Student Batch : ")
   val Batch = readln()
   print("Student College Name : ")
   val CollegeName = readln()
   print("Student University Name : ")
   val UniversityName = readln()
   print("Student Age : ")
   val Age = readln().toInt()


   println("\n****************************\n")
   println("Student' Data : ")
   println("Enrollment No. : $Enrollment")
   println("Name : $Name")
   println("Age : $Age")
   println("Branch : $Branch")
   println("Class : $Class")
   println("Batch : $Batch")
   println("College Name : $CollegeName")
   println("University Name : $UniversityName")
}
